### ISSUE TITLE
Adding disabled traps crashes game when loading that level

### ISSUE THREAD

**Issue by AlphaDraxonis** [QuasiStellar/custom-pixel-dungeon#3]
Basically the title. When I add disabled (inactive) traps to a custom level layout, the game always crashes when loading that level.
The problem is in class ClustomLevel in line 269.
It crashes because Level#disarmTrap() is not the correct call to disarm traps and just one simple feature test would have been enough to find this mistake.
First, disarmTraps sets the terrain to INACTIVE_TRAP which is not required because you just checked if the terrain is already that. But this call also assumes that Dungeon.level is not null, but at that position it is always null (bc Dungeon.newLevel() sets it to null), so this is what is causing the crash.
And second, the class Trap has a boolean variable active which should be false for inactive traps, and for example Trap#disarm() correctly changes that.
So to fix the issue, you should only call GameScene.updateMap(int cell) and trap.active=false, but do not change the terrain.
And again, please make sure to call every single line of code you are adding at least once in a real scenario so that mistakes like this don't end up in a release version.

**Comment by QuasiStellar** [comment]
thanks, will check

**Comment by QuasiStellar** [comment]
fixed in 1.0
